CREATE TABLE fornecedores (
    ID TEXT PRIMARY KEY ,
    Nome VARCHAR(255) NOT NULL,
  	Contato VARCHAR(100) NOT NULL,
    Telefone VARCHAR(20),
    Email VARCHAR(100),
	Rua VARCHAR(100) NOT NULL,
	Bairro VARCHAR(100) NOT NULL,
	Cidade VARCHAR(100) NOT NULL,
	Estado VARCHAR(2) NOT NULL,
	cep VARCHAR(8) NOT NULL
);